version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=guilhermerosa/locadorafilmes
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI
      - echo Writing image definitions file...
      - printf '[{"name":"locadora-filmes","imageUri":"%s"}]' $REPOSITORY_URI > imagedefinitions.json
artifacts:
    files: imagedefinitions.json